services:
  subsea-generator:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: subsea-topology-api
    restart: always
    ports:
      - "8081:80"
    environment:
      - FLASK_ENV=production
    networks:
      - subsea_net

networks:
  subsea_net:
    driver: bridge